Add pay to mint feature to nft minting
oursky/likecoin-chain pull request #179
Opened 2022-04-07 04:13 UTC by hochiw

- Added genesis param 'MintPriceDenom'
- Added the ability to mint nft as a non-owner when nft class mint price is larger than zero
- Retain owner checking mechanics when mint price is zero such that only the owner of the class is able to mint nfts
- Added test cases for when mint price is larger than zero and minter has sufficient funds vs insufficient funds

- Manually tested with a single node locally
    - Class with mint price = 0, minter is owner, can mint
    - Class with mint price = 0, minter is not owner, cannot mint
    - Class with mint price = 5000000000, minter is owner, can mint
    - Class with mint price = 5000000000, minter is not owner, minter has insufficient funds, cannot mint
    - Class with mint price = 5000000000, minter is not owner, minter has sufficient funds, can mint

Note: it seems that the mint price doesn't appear in the transaction message when minting an nft as a non-owner, it's expected based on how we coded it but im not sure if it is a necessary information to show since iirc stargaze doesn't do it as well.

based on #171 
refs #150

2022-04-07 09:09 UTC, chihimng commented
@hochiw 
I think we should decouple whether the class for public pay-to-mint & the price, so we can allow the use case where a class is for free claiming

2022-04-07 09:10 UTC, chihimng commented
sorry should have discussed more before implementation 🙇

2022-04-19 19:09 UTC, chihimng requested changes
Also we might need to update some terminology after latest plan at #192

2022-04-19 19:09 UTC, chihimng commented on x/likenft/keeper/msg_server_mint_nft_test.go
> +func TestMintPayToMintNFTNormal(t *testing.T) {
Did we cover disabled pay to mint?

2022-04-20 06:05 UTC, hochiw commented
@chihimng updated, also refactored a little bit to prevent calling `GetContentIdRecord` twice.

2022-04-20 08:58 UTC, chihimng approved these changes

2022-04-20 09:08 UTC, merged