Add classes by account unittests for nft classes
oursky/likecoin-chain pull request #201
Opened 2022-04-19 04:56 UTC by hochiw

refs #198 #199

2022-04-19 19:20 UTC, chihimng requested changes

2022-04-19 19:20 UTC, chihimng commented on x/likenft/keeper/msg_server_new_class_test.go
>  func TestNewClassInvalidIscn(t *testing.T) {
do we need another case for invalid user address with account parent type?

2022-04-20 06:20 UTC, hochiw commented
@chihimng updated :adore2x:

2022-04-20 09:01 UTC, chihimng approved these changes

2022-04-20 09:09 UTC, chihimng commented on x/likenft/keeper/class_validations.go
> +			return types.ClassParentAndOwner{}, sdkerrors.ErrInvalidAddress.Wrapf("%s", err.Error())
👍

2022-04-20 09:10 UTC, merged