Fix `starport app serve` throws could not find app.go
oursky/likecoin-chain pull request #221
Opened 2022-04-25 01:36 UTC by chihimng

Ref oursky/likecoin-chain#220

Add missing interface used by starport to search for app impl

Testing done:
- Tested issue resolved in starport v0.19.5
- Tested issue resolved in ignite cli v0.20.4 (they renamed starport along with the tendermint org recently)

2022-04-25 18:47 UTC, hochiw approved these changes

2022-04-27 04:17 UTC, rickmak requested changes
Please also update the README to use `ignite chain serve`.

2022-04-27 05:39 UTC, chihimng commented
> Please also update the README to use `ignite chain serve`.

@rickmak updated

2022-04-28 03:50 UTC, rickmak commented
Close via https://github.com/likecoin/likecoin-chain/pull/69

2022-04-28 03:50 UTC, closed without merging