Add check for max supply when creating mintable nft
oursky/likecoin-chain pull request #233
Opened 2022-05-10 03:33 UTC by chihimng

Ref oursky/likecoin-chain#227

Test cases to be added later along with whole blindbox feature

2022-05-10 16:18 UTC, hochiw requested changes

2022-05-11 08:26 UTC, chihimng commented on x/likenft/keeper/msg_server_common_mintable_nft.go
> +	// Check class parent relation is valid and current user is owner
updated

2022-05-11 08:26 UTC, chihimng commented on x/likenft/keeper/msg_server_common_mintable_nft.go
> +	// Check class parent relation is valid and current user is owner
i'm not sure if further refactoring will help much tho 🤔

2022-05-13 09:36 UTC, hochiw approved these changes

2022-05-13 09:36 UTC, merged